spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${LOCAL_NAVER_CLIENT_ID}
            client-secret: ${LOCAL_NAVER_CLIENT_SECRET}
            redirect-uri: ${LOCAL_NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: name, email, nickname
            client-name: naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jwt:
    secret: ${JWT_SECRET}